### ISSUE TITLE
option to query just received messages only?

### ISSUE THREAD

**Issue by mkinney** [lmatte7/meshtastic-go#10]
There's an option in the *info* subcommand to show only the "Recieved Messages:"? If not, could that be added?

Note: Recieved should be spelled "Received".

I really like this tool! Good job!

**Comment by lmatte7** [comment]
Hi there! Thanks for contributing and opening and issue. You can view received messages as they come in with the `messages recv` command. I didn’t include it in the info command because the radios don’t reliably store messages in a way that’s easily retrieved.
