### ISSUE TITLE
change character limit from 240?

### ISSUE THREAD

**Issue by mkinney** [lmatte7/meshtastic-go#12]
Came up in chat today that the message limits are less than 240. 237 is value in proto bufs, but when testing, the various devs found 228 is probably more realistic for things like emojis.

![message_limits](https://user-images.githubusercontent.com/2219838/142962575-fb1f9ad9-d894-47a2-a2b3-1fd23bf0f4b2.png)

Not sure if you want to change the text or not:
https://github.com/lmatte7/meshtastic-go/blob/9ade4f0ef7bcdce0b94c2fa614914b31ee179076/cli.go#L74

**Comment by lmatte7** [comment]
That's a good callout, thanks for mentioning it! Since this isn't an immediate problem I'll bundle it into the next larger release. Also if there are any conversations you want to tag me in on the discord my username on there is the same as on here.
