### ISSUE TITLE
Running on windows 11

### ISSUE THREAD

**Issue by jasonfen** [lmatte7/meshtastic-go#18]
Downloaded latest meshtastic-go.exe on my windows 11 computer.  When I run it says:

Program 'meshtastic-go.exe' failed to run: The specified executable is not a valid application for this OS platform.At
line:1 char:1
+ .\meshtastic-go.exe
+ ~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\meshtastic-go.exe
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by lmatte7** [comment]
Thank you for reporting. I used a new version of Go so it's possible some of the windows compilation issues were changed and are causing errors. Let me dust off my windows machine and I'll take a look.

**Comment by lmatte7** [comment]
Thanks you for reporting! This is fixed in the [newest](https://github.com/lmatte7/meshtastic-go/releases/tag/v0.2.1) release
