### ISSUE TITLE
'info' gives a seg fault

### ISSUE THREAD

**Issue by sigtel** [lmatte7/meshtastic-go#19]
Running ./meshtastic_go_linux_arm64 --port "192.168.x.xxx" info gives a segmentation fault during the node list and before the channel info on one of my nodes, not the other. Other functions seem fine. The node in question sees around 130 nodes so the list is long, output below. System is a Raspberry Pi 4, 4Gb, 64-bit Bullseye.

Nodes in Mesh:
... 77 nodes list fine, and then:

| 3806565296     | N/A            | panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x26f70c]

goroutine 1 [running]:
main.printNodes({0x40000ec008, 0x64, 0x322a62?})
	/Users/Duke/repos/meshtastic-go/info.go:158 +0x44c
main.printRadioInfo({0x40001adb08, 0x83, 0x400018f8b8?})
	/Users/Duke/repos/meshtastic-go/info.go:223 +0x678
main.getRadioInfo({{{0x0, 0x0}, {0x38e3b8, 0x400010c140}, 0x1}})
	/Users/Duke/repos/meshtastic-go/info.go:106 +0x50
main.showAllRadioInfo(0x4000103070?)
	/Users/Duke/repos/meshtastic-go/info.go:33 +0x98
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0x40001449c0, 0x400011ef40)
	/Users/Duke/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:439 +0x7f4
github.com/urfave/cli/v2.(*Command).startApp(0x4000199560, 0x400011ef40)
	/Users/Duke/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:278 +0x650
github.com/urfave/cli/v2.(*Command).Run(0x400011ed00?, 0x3?)
	/Users/Duke/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:94 +0x74
github.com/urfave/cli/v2.(*App).RunContext(0x4000144820, {0x38c0b0, 0x625ea0}, {0x400011e040, 0x4, 0x4})
	/Users/Duke/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x844
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/Duke/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.Init()
	/Users/Duke/repos/meshtastic-go/cli.go:322 +0x1d74
main.main()
	/Users/Duke/repos/meshtastic-go/main.go:6 +0x1c

**Comment by lmatte7** [comment]
Ohhh this is a very cool error! I have no where near that many radios to test with, thank you for reporting!

Would you mind providing which version of the CLI you're using and I'll dig in?

**Comment by sigtel** [comment]
Sure, v0.2

**Comment by sigtel** [comment]
FYI I just tried there amd64 version on a Linux box and it fails in just the same way as the arm64 / Raspberry Pi version.

**Comment by lmatte7** [comment]
Thanks for the extra information. I bet this is from a Node that hasn't populated all of it's information yet. 

Do you notice it always fails around the same node, or does it happen randomly as they're being listed?

**Comment by sigtel** [comment]
I tried a few times and yes it always fails at the same node. The last two nodes (the last one being where the segfault occurs) are listed in the table as:

| 3663495376     | Nah Then Thee  | N/A            | N/A            | N/A            | |
| 3806565296     | N/A            |


And the data for these (further up in the output):

Node Info
state                    {{} [] [] <nil>}
sizeCache                0
unknownFields            []
Num                      3663495376
User                     id:"!da5c80d0"  long_name:"Nah Then Thee "  short_name:"EyUp"  macaddr:"4\xb7\xda\\\x80\xd0"  hw_model:HELTEC_V3  role:ROUTER_CLIENT
Position                 <nil>
Snr                      -17
LastHeard                1712314960
DeviceMetrics            battery_level:86  voltage:4.03  channel_utilization:3.8866665  air_util_tx:3.3887222
Channel                  0
ViaMqtt                  false
HopsAway                 0


Node Info
state                    {{} [] [] <nil>}
sizeCache                0
unknownFields            []
Num                      3806565296
User                     <nil>
Position                 latitude_i:533650000  longitude_i:-12040000  time:1712313206
Snr                      -14
LastHeard                1712313221
DeviceMetrics            <nil>
Channel                  0
ViaMqtt                  false
HopsAway                 0

I only have wifi / web access to the node and I can't see any way to reset the nodedb.

**Comment by lmatte7** [comment]
That's really helpful, thank you! I think it'll be a fairly easy fix and will post an update here when I have more updates.

**Comment by sigtel** [comment]
Ah it has changed - the last time I tried it failed after listing just a few nodes in the table:

| 3806565344     | N/A            | panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x26f70c]

Different node, same failure mode though

**Comment by satscape** [comment]
Linux too, here's some more techie info:
(Very distant node if that helps 80 Km)

`| 3662957532     | pip1 yagi 🏠    | panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x82c9d5c]

goroutine 1 [running]:
main.printNodes({0x9807448, 0x21, 0x46})
	/Users/Duke/repos/meshtastic-go/info.go:158 +0x68c
main.printRadioInfo({0x9807328, 0x40, 0x46})
	/Users/Duke/repos/meshtastic-go/info.go:223 +0x755
main.getRadioInfo({{{0x0, 0x0}, {0x83ba0d0, 0x9898950}, 0x1}})
	/Users/Duke/repos/meshtastic-go/info.go:106 +0x55
main.showAllRadioInfo(0x989d2e0)
	/Users/Duke/repos/meshtastic-go/info.go:33 +0x90
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0x98d42a8, 0x989d200)
	/Users/Duke/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:439 +0xa3b
github.com/urfave/cli/v2.(*Command).startApp(0x98aea08, 0x989d200)
	/Users/Duke/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:278 +0x5ff
github.com/urfave/cli/v2.(*Command).Run(0x98aea08, 0x989d200)
	/Users/Duke/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:94 +0x8b
github.com/urfave/cli/v2.(*App).RunContext(0x98d41c8, {0x83b95a8, 0x85f2460}, {0x989c1c0, 0x4, 0x4})
	/Users/Duke/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xa73
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/Duke/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.Init()
	/Users/Duke/repos/meshtastic-go/cli.go:322 +0x1c12
main.main()
	/Users/Duke/repos/meshtastic-go/main.go:6 +0x17`

**Comment by lmatte7** [comment]
Fantastic, thank you! I'm still looking into this to find a reliable way to prevent the errors so the information is appreciated

**Comment by lmatte7** [comment]
Thanks to everyone for reporting and helping to diagnose! This is fixed in the [newest](https://github.com/lmatte7/meshtastic-go/releases/tag/v0.2.1) reelase
