### ISSUE TITLE
Cannot set Channel Index to send on

### ISSUE THREAD

**Issue by apleschu** [lmatte7/meshtastic-go#21]
Environment: Raspberry Pi native meshatsticd daemon

Radio Settings: 
Radio Metadata
FirmwareVersion          2.3.9.f06c56a
DeviceStateVersion       22
CanShutdown              false
HasWifi                  true
HasBluetooth             false
HasEthernet              false
Role                     CLIENT
PositionFlags            811
HwModel                  PORTDUINO
HasRemoteHardware        false

It seems there is no way to determine on which channel a specific message is going to be sent. Currently it always sends the message on channel 0

**Comment by lmatte7** [comment]
You are absolutely correct, thank you for opening an issue! My tests for messages passed without needing upgrades from the old to new version so I overlooked this. I'll start working on a fix (which should be pretty simple)

**Comment by lmatte7** [comment]
Fixed in the latest relase
