### ISSUE TITLE
JSON option not working on "info nodes"

### ISSUE THREAD

**Issue by hcsaustrup** [lmatte7/meshtastic-go#26]
```
$ meshtastic-go --version
meshtastic-go version v0.2
$ meshtastic-go -p xx.xx.xx.xx info --json nodes

Nodes in Mesh:
=========================================================================================================================================================================================
| Node Number    | User           | Battery        | Altitude       | Latitude       | Longitude      |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
...
```

**Comment by lmatte7** [comment]
Thank you for reporting! I think this is tied to a bug on a newer meshtastic release. Would you mind giving what version of the firmware you're using?

**Comment by hcsaustrup** [comment]
Ah yes, of course. I forgot which unit I tested on, but it's either 2.4.1 or a preview version of 2.5.0.

**Comment by hcsaustrup** [comment]
The issue exists with firmware 2.4.2.5b45303.

**Comment by lmatte7** [comment]
Hello! I wanted to post an update that I haven't forgotten about this, things have just been very busy 😂 I'm hoping I'll have time next week to diagnose what's going on and cut a release

**Comment by lmatte7** [comment]
This should be fixed in the newest [release](https://github.com/lmatte7/meshtastic-go/releases/tag/v0.2.3). I'm going to close the issue for now, but if you're still seeing issues after trying the new version please let me know 😃
