### ISSUE TITLE
message recv not working (or i'm using it wrong)

### ISSUE THREAD

**Issue by andrewheadricke** [lmatte7/meshtastic-go#27]
Just started playing around with sending and receiving messages. Sending appears to work fine, but receiving just sits there and never shows messages.

I'm testing using a private node to node message which are PKI encrypted.

Any idea what could be the issue?

**Comment by lmatte7** [comment]
Hello! Sorry for the delayed response. Would you mind including what firmware you're using on the devices?

**Comment by lmatte7** [comment]
Oops I closed the wrong issue, sorry about that

**Comment by andrewheadricke** [comment]
Pulled the lastest changes and its working now. Thanks!
